version: "3.6"


services:
  base: &base
    build: .
    networks:
      - devops-network
    volumes:
      - .:/usr/src/app

  devops-web:
    <<: *base
    container_name: devops-web
    ports:
      - "8010:8000"
    stdin_open: true
    tty: true
    command: ["poetry", "run", "uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

networks:
  devops-network:
    external: true
