apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

namespace: staging

resources:
- namespace.yaml
- service-active.yaml
- service-preview.yaml
- rollout.yaml

images:
- name: public.ecr.aws/g3n2k4q3/devops_hobbies
  newTag: 5944c234971ef3c247df04b496adae41d4542e2e

commonLabels:
  commit: 5944c234971ef3c247df04b496adae41d4542e2e
