apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

namespace: staging

resources:
- namespace.yaml
- ingress.yaml
- service-active.yaml
- service-preview.yaml
- rollout.yaml

images:
- name: public.ecr.aws/g3n2k4q3/devops_hobbies
  newTag: eb6d5ec

commonLabels:
  commit: eb6d5ec
