
name: Run test and updates kustomization.yaml image tag with current commit sha

permissions:
 id-token: write
 contents: write     # allows GA commit changes

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    name: Run tests and update image tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Kustomize update image's tag
        run: |
          cd deploy
          kustomize edit set image public.ecr.aws/g3n2k4q3/devops_hobbies:${GITHUB_SHA}
          kustomize edit set label commit:${GITHUB_SHA}

          git config user.name github-actions
          git config user.email github-actions@github.com

          echo "GIT STATUS........."
          git status
          git branch
          git log

          git add .
          git commit --amend --no-edit
          git push
        
        
        
        

#      - name: Setup Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Install requirements
#        run: |
#          pip install --upgrade pip && pip3 install "poetry==1.3.2" --no-cache-dir
#          poetry config virtualenvs.create false
#          poetry install --no-interaction --no-ansi
#      - name: Run Tests
#        env:
#          ENVIRONMENT: testing
#        run: |
#          python manage.py test

